MandarinMedien\MMCmfNodeBundle\Entity\NodeRoute:
    type: entity
    table: null
    inheritanceType: SINGLE_TABLE
    indexes:
        uri_index:
            columns: [ route ]
    discriminatorMap:
        default: NodeRoute
        auto: AutoNodeRoute
        alias: AliasNodeRoute
        redirect: RedirectNodeRoute
        external: ExternalNodeRoute

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        route:
            type: string
            length: 255

        domains:
            type: json_array
            nullable: true

    lifecycleCallbacks: {  }
