MandarinMedien\MMCmfNodeBundle\Entity\Node:
    type: entity
    table: null
    inheritanceType: JOINED
    repositoryClass: MandarinMedien\MMCmfNodeBundle\Repository\NodeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: false
        position:
            type: integer
            gedmo:
                - sortablePosition
        visible:
            type: boolean

    oneToMany:
        nodes:
            targetEntity: MandarinMedien\MMCmfNodeBundle\Entity\Node
            mappedBy: parent
            orderBy: { 'position': 'ASC' }
            cascade:
                - all

    manyToOne:
        parent:
            targetEntity: MandarinMedien\MMCmfNodeBundle\Entity\Node
            joinColumn:
                  onDelete: "SET NULL"
            inversedBy: nodes
            nullable: true
            gedmo:
                - sortableGroup


    lifecycleCallbacks: {  }
