services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\ParamConverterInterface:
            tags: [{name: request.param_converter, priority: -1}]

    MandarinMedien\MMCmfNodeBundle\:
        resource: "../../*"
        exclude: "../../{Entity,Resources,Model,Exception}"

    MandarinMedien\MMCmfNodeBundle\Controller\:
        resource: "../../Controller"
        tags: [controller.service_arguments]


    MandarinMedien\MMCmfNodeBundle\Configuration\NodeRegistry:
        public: true

    MandarinMedien\MMCmfNodeBundle\Configuration\TagRegistry:
        public: true

    MandarinMedien\MMCmfNodeBundle\Factory\NodeFactory:
        public: true

    MandarinMedien\MMCmfNodeBundle\Factory\NodeRouteFactory:
        public: true

    MandarinMedien\MMCmfNodeBundle\Manager\NodeRouteManager:
        public: true

    MandarinMedien\MMCmfNodeBundle\Resolver\NodeResolver:
        public: true

    MandarinMedien\MMCmfNodeBundle\Resolver\NodeRouteResolver:
        public: true

    MandarinMedien\MMCmfNodeBundle\Resolver\NodeDefinitionResolver:
        public: true

    MandarinMedien\MMCmfNodeBundle\Resolver\TemplateDefinitionResolver:
        public: true

    MandarinMedien\MMCmfNodeBundle\Templating\TemplateManager:
        public: true

    Gedmo\Sortable\SortableListener:
        tags: [{ name: doctrine.event_subscriber, connection: default }]
        calls:
            - ['setAnnotationReader', ['@annotation_reader']]


    # configure the visibilty filter on request
    MandarinMedien\MMCmfNodeBundle\Doctrine\Filter\VisibilityFilterConfigurator:
        calls: [{method: setRoles, arguments: [["ROLE_ADMIN", "ROLE_USER"]]}]
        tags: [{ name: kernel.event_listener, event: kernel.request }]


    # Doctrine Event Listener
    MandarinMedien\MMCmfNodeBundle\EventListener\NodeRouteListener:
        tags:
            - {name: doctrine.event_listener, event: prePersist}
            - {name: doctrine.event_listener, event: onFlush}
            - {name: doctrine.event_listener, event: postFlush}

