services:
      # Validation Constraints
      mm_cmf_node.validator.no_node_recursion:
          class: MandarinMedien\MMCmfNodeBundle\Validator\NoNodeRecursionValidator
          calls:
              - ["setManager", [@doctrine.orm.entity_manager]]
          tags:
              - { name: validator.constraint_validator, alias: "no_node_recursion" }
