services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MandarinMedien\MMCmfNodeBundle\Factory\NodeFactory:
        public: true

    MandarinMedien\MMCmfNodeBundle\Factory\NodeRouteFactory:
        pubic: true

    MandarinMedien\MMCmfNodeBundle\Manager\NodeRouteManager:
        public: true

    MandarinMedien\MMCmfNodeBundle\Resolver\NodeResolver:
        public: true

    MandarinMedien\MMCmfNodeBundle\Templating\TemplateManager:
        public: true

    MandarinMedien\MMCmfNodeBundle\Request\NodeParamConverter:
        tags:
            - {name: request.param_converter, priority: 1, converter: mm_cmf_node.node_converter }

    MandarinMedien\MMCmfNodeBundle\Request\NodeRouteParamConverter:
        tags:
            - {name: request.param_converter, priority: 1, converter: MandarinMedien\MMCmfRoutingBundle\Request\NodeRouteParamConverter }

    MandarinMedien\MMCmfNodeBundle\Twig\MMCmfNodeRenderExtension:
        tags:
            - {name: twig.extension}

    mm_cmf_routing.node_route_factory:
        alias: MandarinMedien\MMCmfNodeBundle\Factory\NodeRouteFactory
        public: true
        deprecated: true

    mm_cmf_routing.node_route_manager:
        alias: MandarinMedien\MMCmfNodeBundle\Manager\NodeRouteManager
        public: true
        deprecated: true

    mm_cmf_node.factory:
        alias: MandarinMedien\MMCmfNodeBundle\Factory\NodeFactory
        public: true
        deprecated: true

    mm_cmf_routing.node_resolver:
        alias: MandarinMedien\MMCmfNodeBundle\Resolver\NodeResolver
        public: true
        deprecated: true

    mm_cmf_content.template_manager:
        alias: MandarinMedien\MMCmfNodeBundle\Templating\TemplateManager
        public: true
        deprectaed: true

    mm_cmf_node.gedmo.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - ['setAnnotationReader', ['@annotation_reader']]

    # configure the visibilty filter on request

    MandarinMedien\MMCmfNodeBundle\Doctrine\Filter\VisibilityFilterConfigurator:
        calls:
            - {method: setRoles, arguments: [["ROLE_ADMIN", "ROLE_USER"]]}
        tags:
            - { name: kernel.event_listener, event: kernel.request }


    # Validation Constraints
    MandarinMedien\MMCmfNodeBundle\Validator\Constraint\NodeRouteUniqueValidator:
        tags:
            - { name: validator.constraint_validator, alias: "node_route_unique" }


    # Doctrine Event Listener
    MandarinMedien\MMCmfNodeBundle\EventListener\NodeRouteListener:
        tags:
            - {name: doctrine.event_listener, event: prePersist}
            - {name: doctrine.event_listener, event: onFlush}
            - {name: doctrine.event_listener, event: postFlush}

