<?php

namespace MandarinMedien\MMCmfNodeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{
}
